### ISSUE TITLE
User homepage crashes when trying to edit a created event

### ISSUE THREAD

**Issue by josephdoba** [josephdoba/JoinUs#85]
it appears the issue is stemming from this block of code in ``EventDetails.js`` The latest merge was #84 , but I had discovered it on #83 

    <Avatar
      alt={eventOwner.name}
      src={eventOwner.picture}
      sx={{ width: 56, height: 56 }}
    />
    {eventOwner.name}
  </Typography>

When edit is clicked on from a pre-seeded event, the feature works fine. However, if edit is clicked on a user created event

` console.log(owner(attendeelist, event)); `appears to return undefined.

https://user-images.githubusercontent.com/43016199/195052267-fae6a1ab-ef36-4813-8f2a-df254f6b1afc.mov

**Comment by carmtsang** [comment]
not an issue. i've fixed it. its just the list
